//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenedia.Modules.QoL.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kenedia.Modules.QoL.Strings.common", typeof(common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activated.
        /// </summary>
        internal static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Mouse Scroll.
        /// </summary>
        internal static string AllowManualZoom_Name {
            get {
                return ResourceManager.GetString("AllowManualZoom_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow scrolling with your mouse wheel without triggering zooming out.
        /// </summary>
        internal static string AllowManualZoom_Tooltip {
            get {
                return ResourceManager.GetString("AllowManualZoom_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift + Click on an Item!.
        /// </summary>
        internal static string ClickItem {
            get {
                return ResourceManager.GetString("ClickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deactivated.
        /// </summary>
        internal static string Deactivated {
            get {
                return ResourceManager.GetString("Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable {0}.
        /// </summary>
        internal static string Enable_Name {
            get {
                return ResourceManager.GetString("Enable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable &amp; Load {0}.
        /// </summary>
        internal static string Enable_Tooltip {
            get {
                return ResourceManager.GetString("Enable_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access bar: Direction.
        /// </summary>
        internal static string ExpandDirection_Name {
            get {
                return ResourceManager.GetString("ExpandDirection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction the access bar shall expand to.
        /// </summary>
        internal static string ExpandDirection_Tooltip {
            get {
                return ResourceManager.GetString("ExpandDirection_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force access bar on screen.
        /// </summary>
        internal static string ForceOnScreen_Name {
            get {
                return ResourceManager.GetString("ForceOnScreen_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the access bar is moved outside the game bounds the bar gets moved back inside.
        /// </summary>
        internal static string ForceOnScreen_Tooltip {
            get {
                return ResourceManager.GetString("ForceOnScreen_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Max Zoom.
        /// </summary>
        internal static string ManualMaxZoomOut_Name {
            get {
                return ResourceManager.GetString("ManualMaxZoomOut_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll out as much as possible!.
        /// </summary>
        internal static string ManualMaxZoomOut_Tooltip {
            get {
                return ResourceManager.GetString("ManualMaxZoomOut_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} !.
        /// </summary>
        internal static string RunStateChange {
            get {
                return ResourceManager.GetString("RunStateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Corner Icon.
        /// </summary>
        internal static string ShowCorner_Name {
            get {
                return ResourceManager.GetString("ShowCorner_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show / Hide the Corner Icon of {0}..
        /// </summary>
        internal static string ShowCorner_Tooltip {
            get {
                return ResourceManager.GetString("ShowCorner_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Icon.
        /// </summary>
        internal static string ShowIcon_Name {
            get {
                return ResourceManager.GetString("ShowIcon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0} Icon on the Hotbar.
        /// </summary>
        internal static string ShowIcon_Tooltip {
            get {
                return ResourceManager.GetString("ShowIcon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw the marked item out!.
        /// </summary>
        internal static string ThrowItem {
            get {
                return ResourceManager.GetString("ThrowItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle {0}.
        /// </summary>
        internal static string Toggle {
            get {
                return ResourceManager.GetString("Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use hotkey PAGE-DOWN to zoom out.
        /// </summary>
        internal static string UseHotkeyInsteadOfMouseWheel_Name {
            get {
                return ResourceManager.GetString("UseHotkeyInsteadOfMouseWheel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom on Camera change.
        /// </summary>
        internal static string ZoomOnCameraChange_Name {
            get {
                return ResourceManager.GetString("ZoomOnCameraChange_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out every time the distance between the player and the camera changes for more than 0.25 units.
        /// </summary>
        internal static string ZoomOnCameraChange_Tooltip {
            get {
                return ResourceManager.GetString("ZoomOnCameraChange_Tooltip", resourceCulture);
            }
        }
    }
}
